default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  <<: *default
  database: elovution

test:
  <<: *default
  database: elovution


production:
  <<: *default
  database: elovution
